name: Release dev

on:

  workflow_dispatch:

  push:
  
    branches:
    
    - main
        
jobs:

  release:
  
    runs-on: windows-latest
        
    steps:
    
    - uses: actions/checkout@v2
            
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
            
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
              
    - name: Execute unit tests
      run: dotnet test
              
    - name: Build AuroraPatch
      run: msbuild AuroraPatch /t:Restore /p:Configuration=Release
      
    - name: Zip AuroraPatch
      uses: thedoctor0/zip-release@master
      with:
        filename: 'release.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'