name: Release dev

on:

  workflow_dispatch:
  
    branches:
    
    - master

  push:
  
    branches:
    
    - master
        
jobs:

  release:
  
    runs-on: windows-latest
        
    steps:
    
    - uses: actions/checkout@v2
            
    #- name: Install .NET Core
    #  uses: actions/setup-dotnet@v1
    #  with:
    #    dotnet-version: 5.0.x
    
    #- name: Execute unit tests
    #  run: dotnet test
    
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE
                  
    - name: Restore Packages
      run: nuget restore AuroraPatch.sln
      
    - name: Build AuroraPatch
      run: msbuild AuroraPatch /p:Configuration=Release
      
    - name: Build Lib
      run: msbuild Lib /p:Configuration=Release
       
    - name: Include Lib in AuroraPatch
      run: xcopy Lib\bin\Release AuroraPatch\bin\Release\Patches\Lib\ /E
      
    - name: Zip AuroraPatch
      uses: papeloto/action-zip@v1
      with:
        files: AuroraPatch/bin/Release/
        recursive: true
        dest: AuroraPatch-dev-${{ github.run_number }}.zip
        
    #- name: Zip Lib
    #  uses: papeloto/action-zip@v1
    #  with:
    #    files: Lib/bin/Release/
    #    recursive: true
    #    dest: Lib-dev-${{ github.run_number }}.zip
        
    - name: Create release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: 'latest-dev'
        prerelease: true
        title: 'Latest Development Build ${{ github.run_number }}'
        files: |
          AuroraPatch-dev-${{ github.run_number }}.zip
        #  Lib-dev-${{ github.run_number }}.zip
          