name: Release dev

on:

  workflow_dispatch:
  
    branches:
    
    - master

  push:
  
    branches:
    
    - master
        
jobs:

  release:
  
    runs-on: windows-latest
        
    steps:
    
    - uses: actions/checkout@v2
            
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
            
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
              
    - name: Execute unit tests
      run: dotnet test
              
    - name: Build AuroraPatch
      run: msbuild AuroraPatch /t:Restore /p:Configuration=Release
      
    - run: dir
      
    - name: Zip AuroraPatch
      uses: papeloto/action-zip@v1
      with:
        files: AuroraPatch
        recursive: true
        dest: result.zip