name: Release

on:

  workflow_dispatch:
  
    branches:
    
    - master

  push:
  
    branches:
    
    - master
        
jobs:

  release:
  
    runs-on: windows-latest
        
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE
                  
    - name: Restore Packages
      run: nuget restore AuroraPatch.sln
      
    - name: Build AuroraPatch
      run: msbuild AuroraPatch /p:Configuration=Release
      
    - name: Build Lib
      run: msbuild Lib /p:Configuration=Release
       
    - name: Include Lib in AuroraPatch
      run: xcopy Lib\bin\Release AuroraPatch\bin\Release\Patches\Lib\ /E
      
    - name: Zip AuroraPatch
      uses: papeloto/action-zip@v1
      with:
        files: AuroraPatch/bin/Release/
        recursive: true
        dest: AuroraPatch-dev-${{ github.run_number }}.zip
        
    - name: Create dev release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: 'latest-dev'
        prerelease: true
        title: 'Latest Development Build ${{ github.run_number }}'
        files: AuroraPatch-dev-${{ github.run_number }}.zip
          
    #### When run manually, do a full release
    
    - name: Bump release version
      id: tag_version
      uses: mathieudutour/github-tag-action@v5.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Zip AuroraPatch
      uses: papeloto/action-zip@v1
      with:
        files: AuroraPatch/bin/Release/
        recursive: true
        dest: AuroraPatch-${{ steps.tag_version.outputs.new_version }}.zip
        
    - name: Create release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: false
        title: 'AuroraPatch ${{ steps.tag_version.outputs.new_version }}'
        files: AuroraPatch-${{ steps.tag_version.outputs.new_version }}.zip